# Haskell stack project Github Actions template
# https://gist.github.com/mstksg/11f753d891cee5980326a8ea8c865233
#
# To use, mainly change the list in 'plans' and modify 'include' for
# any OS package manager deps.
#
# Currently not working for cabal-install >= 3
#
# Based on https://raw.githubusercontent.com/commercialhaskell/stack/stable/doc/travis-complex.yml
#
# TODO:
# * cache (https://github.com/actions/cache)
#     but this is too small. native cacheing will come soon
#     https://github.community/t5/GitHub-Actions/Caching-files-between-GitHub-Action-executions/m-p/30974/highlight/true#M630
#     so we can wait for then.
# * support for cabal-install >= 3

name: Haskell Stack Project CI

on:
  push:
  schedule:
  - cron: "0 0 * * 1"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        # use this to specify what resolvers and ghc to use
        plan:
        - { build: cabal, ghc: 8.8.2, cabal-install: "3.0" }   # currently not working for >= 3.0
        # use this to include any dependencies from OS package managers
        include: []
        #- os: macOS-latest
        #  brew: anybrewdeps
        #- os: ubuntu-latest
          #bash: sudo apt-get update
          #apt-get: "happy libblas-dev liblapack-dev libglvnd-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev"

        exclude:
        - os: macOS-latest
          plan:
            build: cabal

    runs-on: ${{ matrix.os }}
    steps:
    - name: Install OS Packages
      run: |
        sudo apt-get update
        sudo apt-get install happy libblas-dev liblapack-dev libglvnd-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev
      
    - uses: actions/checkout@v1

    - name: Setup stack
      uses: mstksg/setup-stack@v2

    - name: Setup cabal-install
      uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.plan.ghc }}
        cabal-version: ${{ matrix.plan.cabal-install }}
      if: matrix.plan.build == 'cabal'

    - name: Install dependencies
      run: |
        set -ex
        case "$BUILD" in
          stack)
            stack --no-terminal --install-ghc $ARGS test --bench --only-dependencies
            ;;
          cabal)
            cabal --version
            cabal update
            PACKAGES=$(stack --install-ghc query locals | grep '^ *path' | sed 's@^ *path:@@')
            # cabal install --only-dependencies --enable-tests --enable-benchmarks --force-reinstalls --ghc-options=-O0 --reorder-goals --max-backjumps=-1 $CABALARGS $PACKAGES
            ;;
        esac
        set +ex
      env:
        ARGS: ${{ matrix.plan.resolver }}
        BUILD: ${{ matrix.plan.build }}

    - name: Build
      run: |
        stack install
        stack build
    - name : Test
      run : |
        stack test
      env:
        ARGS: ${{ matrix.plan.resolver }}
        BUILD: ${{ matrix.plan.build }}
